version: 0.2
            
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn clean package install test
      - mvn surefire-report:report
      - mvn jacoco:report
      - echo build
  post_build:
    commands:
      - echo post_build
      - find ./
reports:
  jacoco-report:
    files:
      - 'test-results/jacoco-coverage-report.xml'
    file-format: 'JACOCOXML'

artifacts:
  files:
    - target/app.jar